import type { Metadata } from 'next'
import { Kumbh_Sans } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import CartProvider from './components/Providers'
import { ClerkProvider } from '@clerk/nextjs'

const kumbh_sans = Kumbh_Sans({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={kumbh_sans.className}>
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
